### ISSUE TITLE
add new feature--auto_save_inteval option is great?

### ISSUE THREAD

**Issue by LaiJingli** [907th/vim-auto-save#13]
this vim plugin works so cool,it auto saves changes on the fly,but some times it's not the action we want,for example: misstroke the keyboard carelessly would also auto save the error changese  which we do not want when in insert mode,and if add the auto_save_interval options it would mitigate it's influnce.

**Comment by leoroos** [comment]
I don't understand what exactly auto_save_interval is supposed to control. Do you want to set a different time update time, do you want to be able to control in which mode auto save is active, e.g. only save in normal mode?

**Comment by LaiJingli** [comment]
auto_save_interval controls  how long the modifications are saved ,but now it autosaves almost instantly which i don't want,i have tried to set the  updatetime=20000 ,and it does not work.

**Comment by leoroos** [comment]
There is no option auto_save_interval. You got multiple possibilities to solve your problem though.

To prohibit vim-auto-save from changing the default update time you have to set

    let g:auto_save_no_updatetime = 1

I personally prefer to not have any save during insert mode so I set

    let g:auto_save_in_insert_mode = 0

Additionally I like to have every change in normal mode immediately saved. Since a few days ago this can be adjusted by defining on what events auto-save works.
By default the active events that trigger a auto save are 

    [ "CursorHold", "InsertLeave" ]

where CursorHold is responsible to save after each updatetime cycle.
But you can change them to anything you want now. E.g.

    let g:auto_save_events = ["InsertLeave", "TextChanged"]

will never save after a specific time interval, but after every change to the text buffer and every time insert mode is left.

**Comment by 907th** [comment]
@LaiJingli Hi!
Some other plugins heavily rely on `updatetime`, so it is better not to set it too high/low.
I'd better prefer to call your option `auto_save_delay`, it can be implemented (e.g. by comparing time elapsed since `TextChanged` and other events). I don't promise that I implement it in near future, sorry (. But plugin's code is simple, and PR is welcome!

**Comment by LaiJingli** [comment]
i got it,sometimes i use vim's undo/redo  operation to get back to the right version.thanks a lot!

**Comment by inside** [comment]
let g:auto_save_events = ["InsertLeave", "TextChanged"]

If you use this configuration, add some text in insert mode, leave insert mode, the file will be saved twice. The TextChanged event is sufficient. Use it like this:

    let g:auto_save_events = ["TextChanged"]

**Comment by leoroos** [comment]
I just tested that assumption with Vim 7.4-1910-1.
After writing something and leaving insert mode does not perform a save.

TextChanged: After a change was made to the text in the
                                current buffer in Normal mode.  That is when
                                b:changedtick has changed.

From the description you should be correct because insert mode changes do affect the changedtick counter. But never the less no TextChanged event seems to be fired.

Try it yourself by adding

`au TextChanged * nested echo "Textchanged was called"`

to your `.vimrc`. The string is not echoed when I enter and leave insert mode. But it is echoed on, as far as I can tell, all other textchange events.

**Comment by inside** [comment]
Hi leoroos,

You're right!!

I guess either I was drunk when I tested these autocommands or I had a vim version prior to `7.4.493` or both. I found this in the git log:

```
% g log -S TextChanged --since="Sun Jul 10 19:22:53 2014 +0200"
commit 086329d3f6b1182b6817433a1c498e1e746d2a3b
Author: Bram Moolenaar <Bram@vim.org>
Date:   Fri Oct 31 19:51:36 2014 +0100

    updated for version 7.4.493
    Problem:    A TextChanged autocommand is triggered when saving a file.
                (William Gardner)
    Solution:   Update last_changedtick after calling unchanged(). (Christian
                Brabandt)
```

Best,
