### ISSUE TITLE
Don't work with "Ctrl + C" way to leave insert mode

### ISSUE THREAD

**Issue by bepolymathe** [907th/vim-auto-save#42]
Hello,

Thank you for this supplement to Vim which I use every day !
Recently, to try to improve keyboard typing comfort, I left the "insert" mode by "Ctrl + c" instead of "escape" touch. 
In this case, it seems that auto-save does not work. Is there a way around the problem?
Thank you in advance for your answer.

**Comment by bepolymathe** [comment]
Just a little up !

**Comment by 907th** [comment]
@bepolymathe Hello! Sorry for the late answer.

I typed `:h i_CTRL-C` in Vim and found that:
```
CTRL-C          Quit insert mode, go back to Normal mode.  Do not check for
                abbreviations.  Does not trigger the InsertLeave autocommand
                event.
```

AutoSave depends on Vim autocommand events `["InsertLeave", "TextChanged"]` by default. Since `CTRL-C` doesn't trigger these events, AutoSave doesn't activate too.

Do you really need to use `CTRL-C` instead of `Esc`? It seems like `CTRL-C` have different semantic than standard `Esc`. `CTRL-C` is more like *break things and don't trigger anything* and `Esc` is a standard way to leave insert-mode. There is also a [question/answer](https://stackoverflow.com/a/5036294/1247092) about `CTRL-C` and `Esc` difference on StackOverflow.

So I think the best solution would be to use `Esc` but may be remap it to some other key on your keyboard. E.g. it is very popular to remap `CapsLock` to `Esc` (and I use it too).

Another solution is changing the list of events for which AutoSave is triggered on. You may find some suggestions in the ["Events" section](https://github.com/907th/vim-auto-save#events) of the README. But I do really think that you should better use good old `Esc` instead.

**Comment by bepolymathe** [comment]
Thank you very much for that answer. 

In fact, the need comes from the fact that I type in bépo (french dvorak in a way) and that Ctlr-C is much more practical than Esc... 

I'll look at what I can do with the "events".... and if it doesn't work, I'll continue to make "escape" from time to time to record.
Thank you for your answer and this plugin !
