### ISSUE TITLE
Seems to stop Syntastic from working

### ISSUE THREAD

**Issue by psy-q** [907th/vim-auto-save#9]
When using [Syntastic](https://github.com/scrooloose/syntastic), normally any configured Syntastic checks are run automatically on saving a file.

With vim-auto-save enabled, however, the Syntastic checks don't seem to fire. Only when using `:w` to manually save a file with vim-auto-save enabled, or when manually executing `:SyntasticCheck` do we get a syntax check.

**Comment by 907th** [comment]
@psy-q Thanks for opening it! Unfortunately I have no time to investigate it now ( but PR is welcome!

**Comment by psy-q** [comment]
I've tried to find out what the issue might be, but I suspect it could also be something in Syntastic, as that is more complex and uses more hooks than vim-auto-save. My VimL isn't good enough to dig deeper at the moment, though :(

**Comment by rambo-panda** [comment]
I have the same problem。

**Comment by 907th** [comment]
@psy-q @rambo-panda I believe it's fixed now. Please, check.

**Comment by psy-q** [comment]
Fantastic, working fine now. Thanks!

**Comment by vasilakisfil** [comment]
Hi! I think there should an option for that! In static language you can't work if syntatic runs everytime you leave insert mode! It was working great before that :)

**Comment by leoroos** [comment]
Hello Vasilakisfil!

If you think this is worthwhile you should open a new issue describing the problem you have when using auto-save together with Syntastic.

There are already configuration options on which events auto save should fire. You can in detail define the events with the `g:auto_save_events` option.  Since this does not seem to be enough to configure your desired behavior, could you additionally describe in detail the kind of behavior you would envision for an integration with Syntastic?

I assume you would want to prevent Syntastic checks to fire on every save, but still automatically to fire on certain points in time/events. So simply disabling it when performing autosave is probably not the solution?
